// AUTO-GENERATED from prisma/init.sql — do not edit by hand.
// Regenerate: npx prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script

export const INIT_STATEMENTS: string[] = [
  "CREATE SCHEMA IF NOT EXISTS \"public\"",
  "CREATE TABLE \"AdminUser\" (\n    \"id\" TEXT NOT NULL,\n    \"email\" TEXT NOT NULL,\n    \"passwordHash\" TEXT NOT NULL,\n    \"role\" TEXT NOT NULL DEFAULT 'admin',\n    \"totpSecretEnc\" TEXT,\n    \"totpEnabled\" BOOLEAN NOT NULL DEFAULT false,\n    \"failedCount\" INTEGER NOT NULL DEFAULT 0,\n    \"lockedUntil\" TIMESTAMP(3),\n    \"passwordChangedAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updatedAt\" TIMESTAMP(3) NOT NULL,\n\n    CONSTRAINT \"AdminUser_pkey\" PRIMARY KEY (\"id\")\n)",
  "CREATE TABLE \"Session\" (\n    \"id\" TEXT NOT NULL,\n    \"userId\" TEXT NOT NULL,\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"lastActiveAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"absoluteExpiresAt\" TIMESTAMP(3) NOT NULL,\n    \"revokedAt\" TIMESTAMP(3),\n    \"ip\" TEXT,\n    \"browser\" TEXT,\n    \"os\" TEXT,\n    \"device\" TEXT,\n\n    CONSTRAINT \"Session_pkey\" PRIMARY KEY (\"id\")\n)",
  "CREATE TABLE \"SessionToken\" (\n    \"id\" TEXT NOT NULL,\n    \"sessionId\" TEXT NOT NULL,\n    \"tokenHash\" TEXT NOT NULL,\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"expiresAt\" TIMESTAMP(3) NOT NULL,\n    \"usedAt\" TIMESTAMP(3),\n\n    CONSTRAINT \"SessionToken_pkey\" PRIMARY KEY (\"id\")\n)",
  "CREATE TABLE \"RecoveryCode\" (\n    \"id\" TEXT NOT NULL,\n    \"userId\" TEXT NOT NULL,\n    \"codeHash\" TEXT NOT NULL,\n    \"usedAt\" TIMESTAMP(3),\n\n    CONSTRAINT \"RecoveryCode_pkey\" PRIMARY KEY (\"id\")\n)",
  "CREATE TABLE \"TrustedDevice\" (\n    \"id\" TEXT NOT NULL,\n    \"userId\" TEXT NOT NULL,\n    \"tokenHash\" TEXT NOT NULL,\n    \"label\" TEXT NOT NULL DEFAULT 'Unknown device',\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"expiresAt\" TIMESTAMP(3) NOT NULL,\n    \"lastUsedAt\" TIMESTAMP(3),\n\n    CONSTRAINT \"TrustedDevice_pkey\" PRIMARY KEY (\"id\")\n)",
  "CREATE TABLE \"PasswordResetToken\" (\n    \"id\" TEXT NOT NULL,\n    \"userId\" TEXT NOT NULL,\n    \"tokenHash\" TEXT NOT NULL,\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"expiresAt\" TIMESTAMP(3) NOT NULL,\n    \"usedAt\" TIMESTAMP(3),\n\n    CONSTRAINT \"PasswordResetToken_pkey\" PRIMARY KEY (\"id\")\n)",
  "CREATE TABLE \"AuditLog\" (\n    \"id\" TEXT NOT NULL,\n    \"type\" TEXT NOT NULL,\n    \"email\" TEXT,\n    \"userId\" TEXT,\n    \"ip\" TEXT,\n    \"country\" TEXT,\n    \"browser\" TEXT,\n    \"os\" TEXT,\n    \"device\" TEXT,\n    \"userAgent\" TEXT,\n    \"detail\" TEXT,\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\n    CONSTRAINT \"AuditLog_pkey\" PRIMARY KEY (\"id\")\n)",
  "CREATE TABLE \"Inquiry\" (\n    \"id\" TEXT NOT NULL,\n    \"name\" TEXT NOT NULL,\n    \"email\" TEXT NOT NULL,\n    \"phone\" TEXT,\n    \"shootType\" TEXT NOT NULL,\n    \"date\" TEXT,\n    \"location\" TEXT,\n    \"budget\" TEXT,\n    \"message\" TEXT NOT NULL,\n    \"status\" TEXT NOT NULL DEFAULT 'new',\n    \"ip\" TEXT,\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\n    CONSTRAINT \"Inquiry_pkey\" PRIMARY KEY (\"id\")\n)",
  "CREATE TABLE \"MediaAsset\" (\n    \"id\" TEXT NOT NULL,\n    \"fileName\" TEXT NOT NULL,\n    \"thumbName\" TEXT NOT NULL,\n    \"width\" INTEGER NOT NULL,\n    \"height\" INTEGER NOT NULL,\n    \"bytes\" INTEGER NOT NULL,\n    \"alt\" TEXT NOT NULL DEFAULT '',\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\n    CONSTRAINT \"MediaAsset_pkey\" PRIMARY KEY (\"id\")\n)",
  "CREATE TABLE \"Testimonial\" (\n    \"id\" TEXT NOT NULL,\n    \"author\" TEXT NOT NULL,\n    \"role\" TEXT,\n    \"quote\" TEXT NOT NULL,\n    \"published\" BOOLEAN NOT NULL DEFAULT false,\n    \"sort\" INTEGER NOT NULL DEFAULT 0,\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\n    CONSTRAINT \"Testimonial_pkey\" PRIMARY KEY (\"id\")\n)",
  "CREATE TABLE \"Setting\" (\n    \"key\" TEXT NOT NULL,\n    \"value\" TEXT NOT NULL,\n\n    CONSTRAINT \"Setting_pkey\" PRIMARY KEY (\"key\")\n)",
  "CREATE TABLE \"PageView\" (\n    \"id\" TEXT NOT NULL,\n    \"day\" TEXT NOT NULL,\n    \"path\" TEXT NOT NULL,\n    \"visitorHash\" TEXT NOT NULL,\n    \"country\" TEXT,\n    \"device\" TEXT,\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\n    CONSTRAINT \"PageView_pkey\" PRIMARY KEY (\"id\")\n)",
  "CREATE UNIQUE INDEX \"AdminUser_email_key\" ON \"AdminUser\"(\"email\")",
  "CREATE INDEX \"Session_userId_idx\" ON \"Session\"(\"userId\")",
  "CREATE UNIQUE INDEX \"SessionToken_tokenHash_key\" ON \"SessionToken\"(\"tokenHash\")",
  "CREATE INDEX \"SessionToken_sessionId_idx\" ON \"SessionToken\"(\"sessionId\")",
  "CREATE UNIQUE INDEX \"RecoveryCode_codeHash_key\" ON \"RecoveryCode\"(\"codeHash\")",
  "CREATE INDEX \"RecoveryCode_userId_idx\" ON \"RecoveryCode\"(\"userId\")",
  "CREATE UNIQUE INDEX \"TrustedDevice_tokenHash_key\" ON \"TrustedDevice\"(\"tokenHash\")",
  "CREATE INDEX \"TrustedDevice_userId_idx\" ON \"TrustedDevice\"(\"userId\")",
  "CREATE UNIQUE INDEX \"PasswordResetToken_tokenHash_key\" ON \"PasswordResetToken\"(\"tokenHash\")",
  "CREATE INDEX \"PasswordResetToken_userId_idx\" ON \"PasswordResetToken\"(\"userId\")",
  "CREATE INDEX \"AuditLog_type_createdAt_idx\" ON \"AuditLog\"(\"type\", \"createdAt\")",
  "CREATE INDEX \"AuditLog_email_createdAt_idx\" ON \"AuditLog\"(\"email\", \"createdAt\")",
  "CREATE INDEX \"AuditLog_createdAt_idx\" ON \"AuditLog\"(\"createdAt\")",
  "CREATE INDEX \"Inquiry_status_createdAt_idx\" ON \"Inquiry\"(\"status\", \"createdAt\")",
  "CREATE UNIQUE INDEX \"MediaAsset_fileName_key\" ON \"MediaAsset\"(\"fileName\")",
  "CREATE INDEX \"PageView_day_idx\" ON \"PageView\"(\"day\")",
  "CREATE INDEX \"PageView_path_day_idx\" ON \"PageView\"(\"path\", \"day\")",
  "ALTER TABLE \"Session\" ADD CONSTRAINT \"Session_userId_fkey\" FOREIGN KEY (\"userId\") REFERENCES \"AdminUser\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE",
  "ALTER TABLE \"SessionToken\" ADD CONSTRAINT \"SessionToken_sessionId_fkey\" FOREIGN KEY (\"sessionId\") REFERENCES \"Session\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE",
  "ALTER TABLE \"RecoveryCode\" ADD CONSTRAINT \"RecoveryCode_userId_fkey\" FOREIGN KEY (\"userId\") REFERENCES \"AdminUser\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE",
  "ALTER TABLE \"TrustedDevice\" ADD CONSTRAINT \"TrustedDevice_userId_fkey\" FOREIGN KEY (\"userId\") REFERENCES \"AdminUser\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE",
  "ALTER TABLE \"PasswordResetToken\" ADD CONSTRAINT \"PasswordResetToken_userId_fkey\" FOREIGN KEY (\"userId\") REFERENCES \"AdminUser\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE"
];
